export const IMPORT_ALL_QUESTIONS = "IMPORT_ALL_QUESTIONS";
export const IMPORT_RANDOM_QUESTIONS = "IMPORT_RANDOM_QUESTIONS";
export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_NEWS = "ADD_NEWS";